# .github/workflows/deploy.yml
name: Automatic CampusTrade Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master # Triggers on push to main or master branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code 📁
        uses: actions/checkout@v4

      - name: Setup Node.js Environment 🟢
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies 🛠️
        run: npm ci || npm install

      - name: Compile and Build Application 🚀
        run: npm run build

      - name: Deploy static assets to GitHub Pages 🌍
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy, Vite builds to dist/
          branch: gh-pages # The branch the action should deploy to
